theme = "lynx"
title = "My Parfum"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "My Parfum"
  headline = "Parfum Terbaik Untuk Kebutuhan Anda"
  image = "author.jpg"
  links = [
    { link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
   # { link = { href = "styles/", text = "All the link styles", target = "_self" } },
   # { github = "https://github.com/jpanther/lynx" },
   # { twitter = "https://twitter.com/jpanther" },
   { tiktok = "https://tiktok.com/@username" },
   { whatsapp = "https://wa.me/phone-number" },
   { telegram = "https://t.me/username" },
   { email = "mailto:hello@your_domain.com" },
   { facebook = "https://facebook.com/username" },
   # { font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
