theme = "lynx"
title = "My Parfum"

enableEmoji = true
disableKinds = ["taxonomy", "term"]
copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "My Parfum"
  headline = "Parfum Terbaik Untuk Kebutuhan Anda"
  image = "my.png"
  links = [
   { tiktok = "https://tiktok.com/@username" },
   { whatsapp = "https://wa.me/phone-number" },
   { telegram = "https://t.me/username" },
   { facebook = "https://facebook.com/username" },
   { email = "mailto:hello@your_domain.com" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
